### ISSUE TITLE
Segmentation Fault 11

### ISSUE THREAD

**Issue by taospartan** [fakufaku/pyramic-demo#1]
When running sim_gsc.py I get a segmentation fault:

`python sim_gsc.py 
/Users/test/Library/Python/2.7/lib/python/site-packages/pyroomacoustics/transform/stft.py:336: UserWarning: Received 516746 samples. Appending 374 zeros for integer multiple of hops.
  extra_samples))
`

`Segmentation fault: 11`

I'm unsure where exactly the error is coming from, would you be able to point me in the correct direction ?

many thanks

Tao

**Comment by taospartan** [comment]
Just for FYI @fakufaku the other 2 test scripts:
```
python3 sim_shape_response.py
python3 sim_match_response.py 
```

Run as expected, with no issues.

Many thanks

Tao

**Comment by fakufaku** [comment]
Tous could could be an issue with the way you installed pyroomacoustics. What is you OS and how did you install it ?
Also, I see that you are running python 2.7. While we still make sure the tests pass for 2.7, we develop mainly with python 3.

Actually, I just noticed that you run the script with python 3, but the error message seems to indicate pyroomacoustics was installed for 2.7. So that might be the problem.

**Comment by taospartan** [comment]
The pyroomacoustics package was installed with pip3, I've uninstalled the 2.7 version of pyroomacoustics with but still get the same result:

`test-MacBook-Pro:sim test$ python3 sim_gsc.py 
/usr/local/lib/python3.7/site-packages/pyroomacoustics/transform/stft.py:336: UserWarning: Received 516746 samples. Appending 374 zeros for integer multiple of hops.
  extra_samples))
Segmentation fault: 11`

I'm running osx Mojave.

many thanks

Tao

**Comment by taospartan** [comment]
Tried on Ubuntu bionic with success
